CREATE TABLE IF NOT EXISTS public.users (
	id SERIAL PRIMARY KEY,
	role_id INTEGER NOT NULL,
	username VARCHAR(100) NOT NULL UNIQUE,
	last_name VARCHAR(100),	
	first_name VARCHAR(100) NOT NULL,
	CONSTRAINT fk_users_roles FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
