version: "3.9"

services:
  db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    networks:
      - seeder

  seeder:
    build:
      context: .
      target: builder
    volumes:
      - ./:/src/app:z
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=users
      - DB_PORT=5432
      - DB_DRIVER=postgres
    entrypoint: ["/bin/bash", "./scripts/entrypoint.sh"]
    networks:
      - seeder

networks:
  seeder:
