name: Run Linters

on: [push, pull_request]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      # Checks out our code locally so we can work with the files.
      - name: Checkout code
        uses: actions/checkout@v3
      # Installs go using a single version.
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.x
      # Runs the default linters provided by golangci-lint plus golint and godot.
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46
          arg s: --enable=golint --enable=godot
